In [1]:
# Importing the required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
#reading csv file and creating a dataframe
df = pd.read_csv("E:\project\Chickpea.data.csv")
df.head()

,Predictor,740,741,742,743,744,745,746,747,748,...,1061,1062,1063,1064,1065,1066,1067,1068,1069,1070
0,Dimtu,1.312229,1.313752,1.315363,1.317040,1.318748,1.320468,1.322220,1.324037,1.325907,...,1.539160,1.540128,1.539360,1.537472,1.535576,1.533732,1.534212,1.536558,1.539456,1.541060
1,Dimtu,1.207945,1.209409,1.211038,1.212806,1.214665,1.216582,1.218553,1.220593,1.222671,...,1.491851,1.492835,1.492130,1.490335,1.488528,1.486766,1.487255,1.489549,1.492376,1.493944
2,Dimtu,1.382931,1.383910,1.385126,1.386556,1.388142,1.389842,1.391645,1.393558,1.395535,...,1.566846,1.567866,1.567114,1.565218,1.563311,1.561454,1.561961,1.564364,1.567328,1.568971
3,Dimtu,1.464557,1.465710,1.466986,1.468363,1.469794,1.471253,1.472753,1.474325,1.475947,...,1.646721,1.647711,1.646850,1.644794,1.642736,1.640737,1.641228,1.643717,1.646801,1.648502
4,Dimtu,1.145023,1.146660,1.148481,1.150452,1.152523,1.154657,1.156848,1.159107,1.161403,...,1.454652,1.455651,1.454998,1.453276,1.451538,1.449841,1.450336,1.452587,1.455357,1.456896

In [3]:
#Na Handling
df.isnull().values.any()

False

In [4]:
df.shape

(950, 332)

In [5]:
Y=df['Predictor']
Y.describe()
Y=pd.DataFrame(Y)

In [6]:
#collecting indepedent variables in X
X = df.iloc[:,1:332]
X_col = X.columns
X.head()

,740,741,742,743,744,745,746,747,748,749,...,1061,1062,1063,1064,1065,1066,1067,1068,1069,1070
0,1.312229,1.313752,1.315363,1.317040,1.318748,1.320468,1.322220,1.324037,1.325907,1.327774,...,1.539160,1.540128,1.539360,1.537472,1.535576,1.533732,1.534212,1.536558,1.539456,1.541060
1,1.207945,1.209409,1.211038,1.212806,1.214665,1.216582,1.218553,1.220593,1.222671,1.224727,...,1.491851,1.492835,1.492130,1.490335,1.488528,1.486766,1.487255,1.489549,1.492376,1.493944
2,1.382931,1.383910,1.385126,1.386556,1.388142,1.389842,1.391645,1.393558,1.395535,1.397497,...,1.566846,1.567866,1.567114,1.565218,1.563311,1.561454,1.561961,1.564364,1.567328,1.568971
3,1.464557,1.465710,1.466986,1.468363,1.469794,1.471253,1.472753,1.474325,1.475947,1.477559,...,1.646721,1.647711,1.646850,1.644794,1.642736,1.640737,1.641228,1.643717,1.646801,1.648502
4,1.145023,1.146660,1.148481,1.150452,1.152523,1.154657,1.156848,1.159107,1.161403,1.163678,...,1.454652,1.455651,1.454998,1.453276,1.451538,1.449841,1.450336,1.452587,1.455357,1.456896

In [7]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
Y_encoded = Y.apply(le.fit_transform)
Y_encoded.head()

   Predictor
0          7
1          7
2          7
3          7
4          7

In [8]:
#Savitzky-Golay filter with second degree derivative.
from scipy.signal import savgol_filter 

sg=savgol_filter(X,window_length=11, polyorder=3, deriv=2, delta=1.0)

C:\Users\LENOVO\Anaconda3\lib\site-packages\scipy\signal\_arraytools.py:45: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  b = a[a_slice]

In [9]:
sg_x=pd.DataFrame(sg, columns=X_col)
sg_x.head()

,740,741,742,743,744,745,746,747,748,749,...,1061,1062,1063,1064,1065,1066,1067,1068,1069,1070
0,0.000069,0.000062,0.000055,0.000048,0.000041,0.000035,0.000022,0.000006,-0.000009,-0.000020,...,-0.000424,-0.000452,-0.000289,8.533263e-07,0.000294,0.000729,0.001164,0.001599,0.002034,0.002469
1,0.000172,0.000149,0.000127,0.000104,0.000081,0.000059,0.000032,0.000005,-0.000019,-0.000036,...,-0.000416,-0.000442,-0.000284,-3.527249e-06,0.000280,0.000703,0.001125,0.001547,0.001969,0.002391
2,0.000269,0.000236,0.000203,0.000170,0.000137,0.000104,0.000066,0.000027,-0.000009,-0.000036,...,-0.000435,-0.000463,-0.000297,-2.368324e-06,0.000296,0.000739,0.001182,0.001625,0.002069,0.002512
3,0.000112,0.000099,0.000085,0.000072,0.000059,0.000045,0.000026,0.000006,-0.000013,-0.000025,...,-0.000449,-0.000478,-0.000304,5.485790e-06,0.000318,0.000783,0.001248,0.001713,0.002178,0.002643
4,0.000186,0.000161,0.000137,0.000112,0.000088,0.000063,0.000035,0.000007,-0.000018,-0.000035,...,-0.000411,-0.000437,-0.000282,-7.838702e-06,0.000270,0.000682,0.001094,0.001506,0.001919,0.002331

In [10]:
# Splitting the data into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =train_test_split(sg_x, Y_encoded,
                                                    test_size=0.2,
                                                    random_state=123,stratify=Y)

In [11]:
from sklearn.tree import DecisionTreeClassifier

Dtree = DecisionTreeClassifier(random_state=52,criterion='entropy',min_samples_split=50)
Dtree_fit=Dtree.fit(X_train, y_train)

In [12]:
y_pred = Dtree.predict(X_test)

In [13]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print("Test Result:\n")        
print("accuracy score: {0:.4f}\n".format(accuracy_score(y_test, y_pred)))
print("Classification Report: \n {}\n".format(classification_report(y_test, y_pred)))
print("Confusion Matrix: \n {}\n".format(confusion_matrix(y_test,y_pred)))

Test Result:

accuracy score: 0.7105

Classification Report:
               precision    recall  f1-score   support

           0       0.69      0.90      0.78        10
           1       1.00      0.70      0.82        10
           2       0.67      0.60      0.63        10
           3       1.00      0.90      0.95        10
           4       0.75      0.90      0.82        10
           5       0.77      1.00      0.87        10
           6       1.00      0.90      0.95        10
           7       0.71      0.50      0.59        10
           8       0.78      0.70      0.74        10
           9       0.40      0.20      0.27        10
          10       0.36      0.50      0.42        10
          11       0.89      0.80      0.84        10
          12       0.50      0.80      0.62        10
          13       0.67      0.80      0.73        10
          14       0.80      0.80      0.80        10
          15       0.57      0.40      0.47        10
          16       0.64      0.90      0.75        10
          17       0.75      0.30      0.43        10
          18       0.82      0.90      0.86        10

   micro avg       0.71      0.71      0.71       190
   macro avg       0.72      0.71      0.70       190
weighted avg       0.72      0.71      0.70       190


Confusion Matrix:
 [[ 9  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  7  0  0  0  0  0  0  0  0  0  0  3  0  0  0  0  0  0]
 [ 0  0  6  0  0  1  0  0  0  0  1  0  0  0  0  0  0  0  2]
 [ 1  0  0  9  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  9  0  0  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  9  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  1  0  5  0  0  0  0  3  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0  7  0  0  0  2  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  2  3  0  0  1  0  3  1  0  0]
 [ 0  0  0  0  0  1  0  0  0  0  5  0  0  2  0  0  2  0  0]
 [ 1  0  0  0  0  0  0  0  0  0  0  8  0  0  1  0  0  0  0]
 [ 0  0  0  0  0  0  0  2  0  0  0  0  8  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  8  1  0  0  1  0]
 [ 0  0  0  0  1  0  0  0  0  0  0  0  0  1  8  0  0  0  0]
 [ 0  0  3  0  0  0  0  0  0  2  1  0  0  0  0  4  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  9  0  0]
 [ 0  0  0  0  1  0  0  0  0  0  3  1  0  0  0  0  2  3  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  9]]

In [16]:
#Reduction of variables using Recursive Feature Elimination(RFE) techineque.

from sklearn.feature_selection import RFE

# RFE with 10 features

rfe_10 = RFE(Dtree ,10)

rfe_10.fit(X_train, y_train)

# selected features
features_bool = np.array(rfe_10.support_)
features = np.array(X_col)
result = features[features_bool]
print('10 selected Features:')
print(result)

C:\Users\LENOVO\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

10 selected Features:
['778' '798' '803' '838' '847' '940' '948' '949' '958' '990']

In [17]:
y_pred = rfe_10.predict(X_test)

print("accuracy score: {0:.4f}\n".format(accuracy_score(y_test, y_pred)))
print("Confusion Matrix: \n {}\n".format(confusion_matrix(y_test, y_pred)))

accuracy score: 0.6579

Confusion Matrix:
 [[9 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0]
 [0 0 6 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 2]
 [1 0 0 9 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 9 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 9 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 9 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 6 0 1 0 0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 7 0 0 0 1 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 2 3 0 0 0 0 5 0 0 0]
 [0 2 0 0 0 0 0 0 0 1 4 0 0 0 0 0 0 3 0]
 [1 0 0 0 0 0 0 0 0 0 2 7 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 2 0 0 0 0 8 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 3 0 0 0 6 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 2 0 7 0 0 0 1 0]
 [0 0 3 0 0 0 0 0 0 1 1 0 0 0 0 4 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 9 1 0]
 [0 0 0 0 1 0 0 0 0 0 3 0 0 0 0 0 0 6 0]
 [0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 1 7]]

In [18]:
# RFE with 15 features

rfe_15 = RFE(Dtree ,15)

# fit with 15 features
RFE15_fit=rfe_15.fit(X_train, y_train)

# selected features
features_bool = np.array(rfe_15.support_)
features = np.array(X_col)
result = features[features_bool]
print('15 selected Features:')
print(result)

C:\Users\LENOVO\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

15 selected Features:
['778' '798' '803' '838' '847' '930' '940' '947' '948' '949' '958' '990'
 '1016' '1023' '1038']

In [19]:
y_pred = rfe_15.predict(X_test)

print("accuracy score: {0:.4f}\n".format(accuracy_score(y_test, y_pred)))
print("Confusion Matrix: \n {}\n".format(confusion_matrix(y_test, y_pred)))

accuracy score: 0.6947

Confusion Matrix:
 [[ 9  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  7  0  0  0  0  0  0  0  0  0  0  3  0  0  0  0  0  0]
 [ 0  0  6  0  0  1  0  0  0  0  1  0  0  0  0  0  0  0  2]
 [ 1  0  0  9  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  9  0  0  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  8  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  1  0  6  0  0  0  0  2  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  1  0  6  0  0  0  2  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  1  3  0  0  1  0  5  0  0  0]
 [ 0  0  0  0  0  1  0  0  0  0  4  0  0  2  0  0  0  3  0]
 [ 1  0  0  0  0  0  0  0  0  0  2  7  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  2  0  0  0  0  8  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  8  1  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  2  0  1  6  0  0  0  1]
 [ 0  0  3  0  0  0  0  0  0  1  1  0  0  0  0  4  1  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  9  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  3  0  0  0  0  0  0  7  0]
 [ 0  0  1  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  8]]

In [20]:
# RFE with 20 features

rfe_20 = RFE(Dtree,20)

# fit with 20 features
rfe_20.fit(X_train, y_train)

# selected features
features_bool = np.array(rfe_20.support_)
features = np.array(X_col)
result = features[features_bool]
print('20 selected Features:')
print(result)

C:\Users\LENOVO\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

20 selected Features:
['751' '778' '798' '803' '827' '838' '847' '864' '930' '940' '944' '947'
 '948' '949' '958' '990' '1016' '1023' '1031' '1038']

In [21]:
y_pred = rfe_20.predict(X_test)

print("accuracy score: {0:.4f}\n".format(accuracy_score(y_test, y_pred)))
print("Confusion Matrix: \n {}\n".format(confusion_matrix(y_test, y_pred)))

accuracy score: 0.7158

Confusion Matrix:
 [[ 9  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  7  0  0  0  0  0  0  0  0  0  0  3  0  0  0  0  0  0]
 [ 0  0  6  0  0  1  0  0  0  0  1  0  0  0  0  0  0  0  2]
 [ 1  0  0  9  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  9  0  0  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  9  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  1  0  6  0  0  0  0  2  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0  7  0  0  0  2  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  1  3  0  0  1  0  5  0  0  0]
 [ 0  0  0  0  0  1  0  0  0  0  5  0  0  2  0  0  2  0  0]
 [ 1  0  0  0  0  0  0  0  0  0  0  8  0  0  1  0  0  0  0]
 [ 0  0  0  0  0  0  0  2  0  0  0  0  8  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  8  1  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  1  8  0  0  0  1]
 [ 0  0  3  0  0  0  0  0  0  1  1  0  0  0  0  4  1  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 10  0  0]
 [ 0  0  0  0  1  0  0  0  0  0  3  1  0  0  0  0  2  3  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  9]]

In [22]:
#Ploting Decision Tree
from sklearn.externals.six import StringIO  
from IPython.display import Image  
from sklearn.tree import export_graphviz
import pydotplus
import os
os.environ["PATH"] += os.pathsep + 'C:/Program Files (x86)/Graphviz2.38/bin/'
dot_data = StringIO()
export_graphviz(Dtree_fit, out_file=dot_data,feature_names=X_col,filled=True,rounded=True)
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
Image(graph.create_png())

ModuleNotFoundError: No module named 'pydotplus'